FROM python:3.7

LABEL Maintainer="sumedhbhat01"

WORKDIR /app

RUN apt-get -y update
RUN apt-get -y install git

COPY requirements.txt requirements.txt

RUN pip3 install -r requirements.txt

COPY . .

CMD [ "python3","main.py" ]

EXPOSE 5000